# Generated by Django 6.0.4 on 2026-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.IntegerField()),
                ('national_id', models.IntegerField()),
            ],
        ),
    ]
